### ISSUE TITLE
TODO: generate full index from a single data file (e.g. yaml file)

### ISSUE THREAD

**Issue by insolor** [dfint/pypi-index#1]
Yaml file concept:

```yaml
package1:
  - name: package1-0.1.0
    url: https://link-url/package1-0.1.0.whl
  - name: package1-0.2.0
    url: https://link-url/package1-0.2.0.whl
package2:
  - name: package2-0.1.0
    url: https://link-url/package2-0.1.0.whl
```
